### PR TITLE
Time-of-flight solver

### PR DESCRIPTION
**Pull request by atgeirr**
This is a first version of the solver class that should be able to compute time-of-flight. It is now used by the Toolbox instead of the mock data. Known limitations:
- does not compute tracer solutions,
- solveLocal() not implemented.

### CODE REVIEW

**Comment by bska** [comment]
I think this is okay, but I don't know that we need full inlining of the solver implementation here.  All loops are big enough that they can (probably) be put into a separate implementation file (`.cpp`) without undue loss of performance.  We'll need to measure, though.  With a separate implementation file we won't have to expose `tarjan.h` to clients of the library.

I also don't particularly like `#include <iostream>` in (public) headers, and get a build failure

```
TracerTofSolver.hpp:225:53: error: ‘fabs’ is not a member of ‘std’
```

(missing `#include <cmath>`) and locally-defined-but-unused-typedefs (`SampleSize`) in `Toolbox::injDiag()` and `Toolbox::prodDiag()` that appear to be leftovers from the mocked implementation.

I'll merge once the `fabs()` build failure is corrected.

**Comment by atgeirr** [comment]
Updated according to review comments.

**Comment by bska** [comment]
> Updated according to review comments.

Thanks.  Just one more thing:

```
TracerTofSolver.cpp: In member function ‘void Opm::FlowDiagnostics::TracerTofSolver::computeOrdering()’:
TracerTofSolver.cpp:103:9: error: ‘unique_ptr’ is not a member of ‘std’
         std::unique_ptr<TarjanSCCResult, Deleter>
         ^
```

We appear to be missing `#include <memory>`.

**Comment by atgeirr** [comment]
Indeed. These things have always been the other way (clang had fewer transitive includes than gcc) for me, but it seems those tables have turned. I'll update.

**Comment by atgeirr** [comment]
Fixed.

**Comment by bska** [comment]
> Fixed.

:+1: 

I'll merge into master.  Thanks a lot.

**Pull request merged**
