### PR TITLE
Import Tarjan Implementation from OPM-Core

### PR DESCRIPTION
**Pull request by bska**
Corresponds to [`tarjan.c`](https://github.com/OPM/opm-core/blob/master/opm/core/transport/reorder/tarjan.c) as of OPM/opm-core@884c5ab.

### CODE REVIEW

**Comment by akva2** [comment]
any history worth retaining ?

**Comment by bska** [comment]
> any history worth retaining ?

Yes, there is.  However, my `git filter-branch` script ended up selecting a larger set of commits than those that touch `tarjan.[hc]`.  I suspect I'm doing something wrong, so I'd appreciate any help you can ~~get~~ give.

I used (well, attempted to use) the following procedure
1. Clone opm-core and remove its `origin`
2. Exclude everything not touching the `opm/core/transport/reorder` directory
   
   ``` sh
   git filter-branch \
       --subdirectory-filter opm/core/transport/reorder \
       --tag-name-filter cat --prune-empty -- --all
   ```
3. Exclude everything not touching `tarjan.[hc]`
   
   ``` sh
   git filter-branch -f --index-filter \
   'git ls-files -s | grep $'\t'tarjan.[hc]$ |
   GIT_INDEX_FILE=$GIT_INDEX_FILE.new \
   git update-index --index-info && \
   mv $GIT_INDEX_FILE.new $GIT_INDEX_FILE || echo "Nothing to do"' \
   --prune-empty --tag-name-filter cat -- --all
   ```

Then I was left with commits mentioning a lot more of the history of opm-core than I really needed **and** a copy of [`reordersequence.h`](https://github.com/OPM/opm-core/blob/master/opm/core/transport/reorder/reordersequence.h) too.

**Comment by akva2** [comment]
your approach is fine.

the problem is that opm-core contains a lot of merges where upstream has 
been merged into the downstream branch prior to the downstream 
branch being merged into upstream.

this destroys ancestry; the changes from upstream that was merged into 
the downstream now show as originating from the downstream branch. thus 
all merge commits where changes to tarjan.c was merged and not rebased 
is now a parent of a commit touching tarjan.[ch] and those will show up, 
including the (possibly empty, prune-empty won't see it cause it's 
applied to the merge commit only) other commits that came in with the merge.

you have to combat this with a parent-filter which prunes empty parents 
(written in ruby cause that's what the interwebs chose);

```
!/usr/bin/ruby
old_parents = gets.chomp.gsub('-p ', ' ')

if old_parents.empty? then
   new_parents = []
else
   new_parents = `git show-branch --independent #{old_parents}`.split
end

puts new_parents.map{|p| '-p ' + p}.join(' ')
```

that (strictly speaking my other filtering approach was a little 
different but it really doesn't matter) will give you 
opm-flowdiagnostics@akva2/import_tarjan_with_history

**Comment by akva2** [comment]
darn, i have to rerun missed a few hidden files.

**Comment by bska** [comment]
> your approach is fine.

Thanks.  That's good to know.

> the problem is that opm-core contains a lot of merges where upstream has been has been merged into the downstream branch prior to the downstream branch being merged into upstream. this destroys ancestry [...]

Okay, that makes sense.  I guess this shows we really didn't know what we were doing when we started to use distributed version control.

**Comment by akva2** [comment]
sorry for delay, phone call.. branch pointed out above is now up to date and should contain only relevant history.

**Comment by akva2** [comment]
and for completeness; i
1) ran your subdirectory filter command
2) ran with the parent filter and

``` bash
#!/bin/bash

test -f tarjan.h && mkdir -p opm/flowdiagnostics/reorder && mv tarjan.* opm/flowdiagnostics/reorder
rm *
```

as tree filter.
3) pulled the result into opm-flowdiagnostics master.
4) rebased on master to drop the merge commit

3 and 4 could have been done in 1 but i forgot --rebase on the pull.

**Comment by bska** [comment]
> ran with the parent filter and
> 
> ``` sh
> #!/bin/bash
> 
> test -f tarjan.h && mkdir -p opm/flowdiagnostics/reorder && mv tarjan.* opm/flowdiagnostics/reorder
> rm *
> ```
> 
> as tree filter.

Cool!  I'll remember that if I need to do something similar in the future.

I'll incorporate your branch into this PR.

**Comment by bska** [comment]
We have the history now (thanks @akva2 !) so I'll self-merge this to get the repository going.

**Pull request merged**
