### PR TITLE
Fixes and debug aides

### PR DESCRIPTION
**Pull request by atgeirr**
With this (and corresponding ert and applications changes), the tof solver is verified against MRST for at least one nontrivial case.

### CODE REVIEW

**Comment by bska** [comment]
I'm a little reluctant about adding `AssembledConnections::write()`.  I don't see the reason this has to be a member function because it can be implemented entirely in terms of the public interface of the class--especially given the restriction that `compress()` must be called prior to calling `write()`.  It would even be more flexible.

Secondly, if we do add such a function--one that is mainly intended as a debugging aid--then it should print one-based indices to support easy import into Octave or MATLAB using the statement

``` matlab
A = spconvert(load('filename'));
```

**Comment by atgeirr** [comment]
I'm not sure I agree about using one-based indices, but for sure the write() method can be made a free function, and I will change that (tomorrow).

**Comment by atgeirr** [comment]
Changed write() to a free `operator<<` function. Still kept the indexing though: I think incrementing to one-based indices would be ok for a`dumpToMatlab` function explicitly written just for that purpose, but this is more general, we might even add an `operator>>` later.

**Comment by bska** [comment]
> [zero-based indexing] is more general

It's not.  Both schemes have the exact same level of generality.  The one-based scheme has the added benefit of being easy to use with the primary debugging facility for matrix-based objects.  Besides, an `operator>>()` function can be aware of the index scheme of `operator<<()`.

That said, I think this can go in, but I'd prefer if the weights were written with more precision.  Something akin to

``` C++
#include <ios>

// ...

std::ostream&
Opm::operator<<(std::ostream& os, const AssembledConnections& ac)
{
    const auto oprec = os.precision(16);
    const auto oflags = os.setf(std::ios_base::scientific);

    // write contents...

    os.precision(oprec);
    os.setf(oflags);

    return os;
}
```

**Comment by atgeirr** [comment]
Updated as requested.

**Comment by atgeirr** [comment]
Hold off a little, I forgot to add `<ios>` inclusion.

**Comment by atgeirr** [comment]
OK, done.

**Comment by bska** [comment]
> OK, done.

Thanks.  Builds and all tests run in all configurations I checked.  I'll merge into master.  Thanks a lot!

**Pull request merged**
