### PR TITLE
Refactor helper classes

### PR DESCRIPTION
**Pull request by atgeirr**
This simplifies some of the helper classes.
 - CellSet construction is now direct.
 - CellSetValues is now `std::map<int, double>`

This results in a fair reduction in code size and complexity.

Note that this PR is based on #24, so to look at its contribution consider the three last commits only. Will remove [WIP] tag in name when #24 is merged.

Requires downstream changes, PR will appear.

### CODE REVIEW

**Comment by atgeirr** [comment]
@JacobStoren, please consider if you find using std::map<int, double> for CellSetValues acceptable. I might be willing to back down on that if presented with strong counterarguments, but we definitely should make it range-for friendly etc.

**Comment by atgeirr** [comment]
This has been rebased on master since #24 was merged, and is ready for review.

**Comment by JacobStoren** [comment]
`std::map` is fine with me. I am also happy with some of the other changes.

**Comment by bska** [comment]
I didn't think about the implications of [`injectorProducerPairVolume()`](https://github.com/atgeirr/opm-flowdiagnostics/blob/6e41b2736493879936f25519552e35c5fdf97baf/opm/flowdiagnostics/DerivedQuantities.cpp#L170-L176) before.  Which is the more common request, a single I/P pair or all I/P pairs in the model?

**Comment by atgeirr** [comment]
> I didn't think about the implications of `injectorProducerPairVolume()` before. Which is the more common request, a single I/P pair or all I/P pairs in the model?

We don't really know yet! I imagine that we might want to add a way to do this in bulk, and that it could be faster than repeatedly calling the currently proposed method, but until we have a concrete need I suggest we make do with the current very simple method.

The same kind of problem will be raised by `injectorProducerPairFlux()` as well, I intend to provide a simple implementation first, and only later add a method for doing it in bulk.

**Comment by bska** [comment]
I just noticed that [`DerivedQuantities.hpp`](https://github.com/OPM/opm-flowdiagnostics/blob/master/opm/flowdiagnostics/DerivedQuantities.hpp) uses `std::vector<>` and `std::pair<>` in its interfaces but does not

``` C++
#include <utility>
#include <vector>
```

In other words, the header relies on transitive inclusion.  I'll merge once that issue is remedied.

**Comment by atgeirr** [comment]
Sure, will fix!

**Comment by atgeirr** [comment]
Fixed.

**Comment by bska** [comment]
> Fixed.

Thanks.  I'll merge this (and downstream OPM/opm-flowdiagnostics-applications#22) into master.

**Pull request merged**
